### ISSUE TITLE
Type hint for `ViewModel::getIterator()`

### ISSUE THREAD

**Issue by func0der** [laminas/laminas-view#73]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary
To satisfy static code analyzers like `phpstan` or `psalm`, we should add a type hint for `ViewModel::getIterator()` to avoid issues like these: https://phpstan.org/r/4b5b2db4-58c5-45c1-878d-f107d605fd69 (PHPStan example. Line 11 and 13: '...type has no value type specified in iterable type...').

This should suffice:

```
    /**
     * Get iterator of children
     *
     * @return ArrayIterator<int, ModelInterface>
     */
    public function getIterator()
    {
        return new ArrayIterator($this->children);
    }
```

How is your stand on this?
This works with PHPStan, but I know Laminas decided to go with Psalm. Is this suitable for Psalm, too?

**Comment by froschdesign** [comment]
@func0der 
> Is this suitable for Psalm, too?

Should be the same with Psalm.

---

This issue report is related to #56 – any help is welcome here!

**Comment by gsteel** [comment]
Thanks @func0der - I agree that ViewModel could/should be iterable. View Model should also implement `IteratorAggregate` and should receive a class-level doc block with `/** @extends IteratorAggregate<array-key, ModelInterface> */`

Additionally, `getIterator` should return `Traversable` both in the doc block and as a return type.

This should also go into 3.0.

The linked PR targets your fork rather than this repo. If you could rebase on <del>`3.0.x`</del> `2.26.x` and submit the PR here, we can review.

**Comment by gsteel** [comment]
Scratch that - serves me right for not looking at existing code properly. Class level doc-blocks would also be an improvement here though:

```php
/**
 * @template TKey of array-key
 * @template TValue of ModelInterface
 * @extends IteratorAggregate<TKey, TValue>
 */
interface ModelInterface extends Countable, IteratorAggregate
```

and

```php
/** @implements ModelInterface<array-key, ModelInterface> */
class ViewModel implements…
```
